sections:
  main:
    display: Main
    fields:
      -
        handle: site_name
        field:
          character_limit: 0
          type: text
          display: 'Site Name'
          instructions: 'Shown in the nav and footer.'
          listable: hidden
          input_type: text
      -
        handle: personality
        field:
          options:
            casual: Casual
            formal: Formal
          inline: true
          type: radio
          instructions: 'Subtly alter the personality of the site.'
          listable: hidden
          display: Personality
      -
        handle: show_signup
        field:
          type: toggle
          instructions: 'Show the newsletter signup form on the blog.show pages.'
          listable: hidden
          display: 'Show Signup'
      -
        handle: social
        field:
          fields:
            -
              handle: name
              field:
                type: text
                display: Name
            -
              handle: url
              field:
                character_limit: 0
                type: text
                display: URL
            -
              handle: icon
              field:
                container: assets
                mode: list
                restrict: true
                folder: site/social-icons
                allow_uploads: true
                max_files: 1
                type: assets
                display: Icon
          mode: table
          add_row: 'Add Link'
          reorderable: true
          type: grid
          instructions: 'Set social media links for the footer.'
          display: Social
          listable: hidden
  footer_content:
    display: 'Footer content'
    fields:
      -
        handle: footer_text
        field:
          always_show_set_button: false
          buttons:
            - h2
            - h3
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - quote
            - anchor
            - image
            - table
          save_html: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          display: 'footer text'
          type: bard
          icon: bard
          listable: hidden
