sections:
  main:
    display: Main
    fields:
      -
        handle: site_name
        field:
          character_limit: 0
          type: text
          display: 'Site Name'
          instructions: 'Shown in the nav and footer.'
          listable: hidden
          input_type: text
      -
        handle: social
        field:
          fields:
            -
              handle: name
              field:
                type: text
                display: Name
            -
              handle: url
              field:
                character_limit: 0
                type: text
                display: URL
            -
              handle: icon
              field:
                container: assets
                mode: list
                restrict: true
                folder: site/social-icons
                allow_uploads: true
                max_files: 1
                type: assets
                display: Icon
          mode: table
          add_row: 'Add Link'
          reorderable: true
          type: grid
          instructions: 'Set social media links for the footer.'
          display: Social
          listable: hidden
  footer_content:
    display: 'Footer content'
    fields:
      -
        handle: footer_text
        field:
          always_show_set_button: false
          buttons:
            - h2
            - h3
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - quote
            - anchor
            - image
            - table
            - code
            - horizontalrule
          save_html: false
          _content_type: html
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          markdown: false
          display: 'footer text'
          type: bard
          icon: bard
          listable: hidden
          sets:
            html_elements:
              display: 'HTML elements'
              fields:
                -
                  handle: page_break
                  field:
                    html: '<br/>'
                    display: 'page break'
                    type: html
                    icon: code
                    listable: hidden
  contact:
    display: Contact
    fields:
      -
        handle: opening_hours
        field:
          antlers: false
          display: 'opening hours'
          type: textarea
          icon: textarea
          listable: hidden
      -
        handle: contact_number
        field:
          input_type: tel
          antlers: false
          display: 'contact number'
          type: text
          icon: text
          listable: hidden
      -
        handle: address
        field:
          antlers: false
          display: address
          type: textarea
          icon: textarea
          listable: hidden
